name: axen_tech_assignment
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  responsive_framework: ^1.4.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.2
  freezed: ^2.4.7
  dio: ^5.4.1
  get_it: ^7.6.7
  retrofit: ^4.1.0
  flutter_bloc: ^8.1.4
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.8.1
  go_router: ^13.2.0
  freezed_annotation: ^2.4.1
  floor: ^1.4.2
  equatable: ^2.0.5
  loader_overlay: ^5.0.0
  persistent_bottom_nav_bar: ^6.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  logger: ^2.1.0
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  floor_generator: ^1.4.2
  
flutter:
  uses-material-design: true